apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    spec:
      containers:
      - name: my-container
        image: ubuntu
        command: ["/bin/bash"]
        args: ["-c","echo welcome to kubernetes job "]
      restartPolicy: Never