apiVersion: v1
kind: ReplicationController
metadata:
  name: myonlineapp-rc
spec:
   replicas: 7
   selector: 
     app: myonlineapp
     version: 2.6.3
   template:                                     
     metadata:
       labels:
          app: myonlineapp
          version: 2.6.3
     spec:
        containers:
        - name: myonlineapp-container
          image: nbktechnosys/myjavaimage11nov22:1
          ports:
          - containerPort: 8080 