apiVersion: apps/v1 #extensions/v1beta1
kind: DaemonSet
metadata:
  name: daemon-pod
spec:
  selector:
    matchLabels:
      app: frontend-webserver
  template:
    metadata:
      labels:
        app: frontend-webserver
    spec:
      containers:
        - name: webserver
          image: nginx:1.14.2
          ports:
          - containerPort: 80