apiVersion: v1
kind: Pod
metadata:
  name: demopod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: USENRAME
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: nginx-data
              # Specify the key associated with the value
              key: username
        - name: DBPASSWORD
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: nginx-data
              # Specify the key associated with the value
              key: password        
  restartPolicy: Never