apiVersion: v1
kind: Pod
metadata:
  name: demopod
spec:
  containers:
    - name: demo-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "sleep 10000" ]
      volumeMounts:
      - name: secret-volume
        mountPath: /etc/config
  volumes:
    - name: secret-volume
      secret:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        secretName: db-data
  restartPolicy: Never