apiVersion: v1
kind: Pod
metadata:
  name: demopod
spec:
  containers:
    - name: demo
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: db-data
              # Specify the key associated with the value
              key: db_username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: db-data
              # Specify the key associated with the value
              key: db_password        
  restartPolicy: Never