apiVersion: v1
kind: ReplicationController
metadata:
  name: myvertex-rc
spec:
   replicas: 3
   selector: 
     app: myvertexapp
     version: 2.6.2
   template:                                     
     metadata:
       labels:
          app: myvertexapp
          version: 2.6.2
     spec:
        containers:
        - name: myonlineapp-container
          image: nbktechnosys/myjavaimage1dec22:2
          ports:
          - containerPort: 8080 
