apiVersion: v1
kind: Service
metadata:
  name:  myonlineapp-svc
  labels:
    app: myvertexapp
    version: 2.6.2
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32000
    protocol: TCP
  selector:
    app: myvertexapp
    version: 2.6.2 